### ISSUE TITLE
Yarn support?

### ISSUE THREAD

**Issue by nedrichards** [alexlarsson/flatpak-npm-generator#1]
Like all great things in the JS ecosystem, there are two competing package management standards. Yarn has it's own yarn.lock file that describes roughly the same set of info as the package-lock.json. [There is controversy here](https://github.com/yarnpkg/yarn/issues/3614) over how to hold these two concepts in tension. Do you think we should add yarn support to a tool like this? Or make a separate `flatpak-yarn-generator` script?

**Comment by alexlarsson** [comment]
The question is, does the yarn tooling let us pre-seed the caches in a similar way so that we can use it?

**Comment by nedrichards** [comment]
Yep, that's the point of the yarn.lock file. [Documentation here](https://yarnpkg.com/lang/en/docs/yarn-lock/). An idle github search brings up a whole host of people using it for things like that, including this rather natty [yarn2nix](https://github.com/moretea/yarn2nix) converter.

Having a quick look at two real world examples of [yarn](https://github.com/alphagov/govuk_elements/blob/master/yarn.lock) and [npm](https://aomedia.googlesource.com/av1-spec/+/HEAD/package-lock.json) files, they look somewhat similar!

**Comment by alexlarsson** [comment]
Yeah, it seems like npm5 added lock file very much influenced by how yarn works.

**Comment by alexlarsson** [comment]
The question is, give an yarn lockfile with:

```
package-1@^1.0.0:
  version "1.0.3"
  resolved "https://registry.npmjs.org/package-1/-/package-1-1.0.3.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
```
We can generate a source with this uri and checksum. However, where do we put the pre-downloaded one so that `yarn install` uses that instead of downloading it from the network.

**Comment by alexlarsson** [comment]
As for wheer to put the yarn support. I think maybe we should add a single flatpak git repo with the tools for all of these things, including the pypi one elad is doing.

**Comment by nedrichards** [comment]
The single repo for `flatpak-tools` (or similar) makes sense. 

In the example above I think you're supposed to use the yarn '[offline mirror](https://yarnpkg.com/blog/2016/11/24/offline-mirror/)' concept, which may be a bit of a faff. (it may be that the config in the post is out of date, [sources are unclear](https://github.com/yarnpkg/yarn/pull/2970))

**Comment by alexlarsson** [comment]
Yeah, that looks similar to the cache npm5 uses, should be easy to do the same thing then.

**Comment by nedrichards** [comment]
Code moved to a separate repo https://github.com/flatpak/flatpak-builder-tools
